# Server
server.port=3000

#Default SpringBoot
spring.application.name=finance-api

#DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/finance-api
spring.datasource.username=postgres
spring.datasource.password=postgres


#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Exibe SQL no console
spring.jpa.show-sql=true

# JWT
app.jwt.secret=${JWT_SECRET:wHLn7mZ7SVXAOyuynJ4H/Fj4CDUdMAKu3JNwXgmZJ8c=}
app.jwt.expiration-ms=86400000